export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUEST_COMMENTS_PENDING = "REQUEST_COMMENTS_PENDING";
export const REQUEST_COMMENTS_SUCCESS = "REQUEST_COMMENTS_SUCCESS";
export const REQUEST_COMMENTS_FAILED = "REQUEST_COMMENTS_FAILED";
